Flowpack:
  TwitterApi:
    authentication:
      application:
        consumerKey: RRiKIZ6gYrIcLJbcEIPMuLEKT
        consumerSecret: rIy0X5CslqrcR6pi13JRCKdJV6r3wJLUiJtic9A7XWMo0XhxGn


TYPO3:
  Flow:
    security:
      authentication:
        providers:
          TwitterOAuthProvider:
            provider: 'Flowpack\TwitterApi\Authentication\TwitterOAuthProvider'
            providerOptions: []
